# Generated by Django 4.0.2 on 2022-02-04 18:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='tag',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Slug',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2022, 2, 4, 18, 3, 29, 670340, tzinfo=utc), verbose_name='*'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=80, verbose_name='title'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.post')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
