# Generated by Django 4.0.2 on 2022-02-06 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_category_post_tag_remove_post_slug_post_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
    ]
