# Generated by Django 4.0 on 2022-01-31 02:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blog_post1_blog_post2_blog_post3_alter_blog_like_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='post1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='post2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='post3',
        ),
        migrations.AlterField(
            model_name='blog',
            name='post',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
